name: bmi_calculator_app
description: "Bmi Calculator App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.2+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  animations: ^2.0.11
  fl_chart: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.4


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/bmi_app_icon2.png"
  min_sdk_android: 21



flutter_native_splash:
  color: "#101010"  # Background color
  image: assets/icon/bmi_app_icon.png  # Optional image
  android: true
  android_gravity: center
  ios_content_mode: center



flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/openSansRegular.ttf